### PR TITLE
Sonar auth

### PR DESCRIPTION
**Pull request by sgrillon14**
Remove this unused method "browser" parameter

### CODE REVIEW

**Comment by JarekLipsko** [comment]
loadAuthentication is called by whom?

**Comment by ArKniiD** [comment]
C'est appelé par gotourl dans browserSteps


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Jarek Lipsko <notifications@github.com> Date : 04/04/2018  09:27  (GMT+01:00) À : NoraUi/NoraUi <NoraUi@noreply.github.com> Cc : Nicolas HALLOUIN <n.hallouin@gmail.com>, Review requested <review_requested@noreply.github.com> Objet : Re: [NoraUi/NoraUi] Sonar auth (#44) 
loadAuthentication is called by whom?

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/NoraUi/NoraUi","title":"NoraUi/NoraUi","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/NoraUi/NoraUi"}},"updates":{"snippets":[{"icon":"PERSON","message":"@JarekLipsko in #44: loadAuthentication is called by whom?"}],"action":{"name":"View Pull Request","url":"https://github.com/NoraUi/NoraUi/pull/44#issuecomment-378506780"}}}

**Comment by JarekLipsko** [comment]
`gotourl` use `usingAuthentication(String url)` but I do not find `loadAuthentication` caller. "browser" parameter is not use in this.

**Comment by ArKniiD** [comment]
The loadAuthentication method is not used anymore in Noraui but can be called from a generated project to inject an auth cookie. It can be useful for special needs

**Comment by ArKniiD** [comment]
I added a new test in AuthUT.java to cover this part.

**Comment by ArKniiD** [comment]
Done ! Sorry for the mistake during the merge

**Pull request merged**
