### PR TITLE
issue66: Split all "Scenario Outline" in Counter feature.

### PR DESCRIPTION
**Pull request by sgrillon14**

### CODE REVIEW

**Comment by ArKniiD** [comment]
I think, I will take this PR into account in version 3.3 version

**Comment by sgrillon14** [comment]
Where put results? Example: user;password;value;foo;result;result ??

Maybe this evolution is not a good idea in fact.

Maybe 3.3.0 version but maybe never (rejected feature).

What do you think about it?

**Comment by sgrillon14** [comment]
I think that we can reject this feature because it is better to focus on parallel execution which is a feature more requested by users.

**Comment by ArKniiD** [comment]
I think this PR can be deleted because all was done in the PR #89

**Comment by sgrillon14** [comment]
resolved by PR #89

**Pull request closed without merging**
