### PR TITLE
ChainableWaits + step numbers + colors + rework driver restart + PageElement & Page cucumber param

### PR DESCRIPTION
**Pull request by ArKniiD**

### CODE REVIEW

**Comment by sgrillon14** [comment]
`/src/main/java/com/github/noraui/utils/Constants.java` move to `/src/main/java/com/github/noraui/Constants.java`  ?

**Comment by sgrillon14** [comment]
```
    @Deprecated
    @Conditioned
    @Et("Je vérifie que {page-element} est présent(\\?)")
    @And("I check that {page-element} is present(\\?)")
    public void checkElementPresent(PageElement pageElement, List<GherkinStepCondition> conditions) throws FailureException, TechnicalException {
        checkElementPresence(pageElement, true);
    }
```

Deprecated => what method should you use now?

**Comment by ArKniiD** [comment]
Replaced by {page-element} {is-isnot} present

**Comment by sgrillon14** [comment]
`{page-element} {is-isnot} present` is not commit

**Comment by ArKniiD** [comment]
Important change to notify: every gherkin parameter referencing a direct element of code as Page & PageElement won't be provided as String but prefixed with a $ character.
For example :` I clear text in 'bakery.DemoPage-input_text_field'` becomes `I clear text in $bakery.DemoPage-input_text_field`

**Pull request merged**
