### PR TITLE
Escape selector double quotes

### PR DESCRIPTION
**Pull request by JimmyTournemaine**
Selector with double quotes will crash the javascript execution

For more informations, see issue #80 

Signed-off-by: Jimmy Tournemaine <jimdeplouz@gmail.com>

### CODE REVIEW

**Comment by sgrillon14** [comment]
@JimmyTournemaine , I add all unit tests.

After this merge of [JimmyTournemaine/NoraUi#1](https://github.com/JimmyTournemaine/NoraUi/pull/1) you can add a message here for Nicolas Reviewer (ArKniiD).

**Comment by JimmyTournemaine** [comment]
@ArKniiD, I merge all UT added by @sgrillon14 on my fork

**Comment by JimmyTournemaine** [comment]
Do I have to close this pull request and open a new one or the merge is automatically included ?

**Comment by sgrillon14** [comment]
It is good that merged automatically. See https://github.com/NoraUi/NoraUi/pull/81/files

We wait now Nicolas validation.


Thank you very much for this contribution. I hope to see you again soon for other developments from your experience feedback.

**Comment by ArKniiD** [comment]
I made the review. > OK

**Pull request merged**
